name: python

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-13, macos-14] #ubuntu-latest, 

    steps:
      - uses: actions/checkout@v4

      # Install Dependencies
      - if: startsWith(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v2
      - uses: actions/setup-python@v5
      - if: startsWith(matrix.os, 'windows')
        run: pip install meson ninja
      - if: startsWith(matrix.os, 'macos')
        name: Install macos dependencies
        run: brew install pkg-config glfw meson
      #- if: startsWith(matrix.os, 'ubuntu')
      #  name: Install dependencies
      #  run: pacman -Syu --noconfirm && pacman -S --noconfirm --needed freetype2 tbb debuginfod wayland dbus libxkbcommon libglvnd meson cmake git wayland-protocols nodejs

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.20.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
